# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

#- script: |
 #   echo Add other tasks to build, test, and deploy your project.
  #  echo See https://aka.ms/yaml
  #displayName: 'Run a multi-line script'
  
#- script: echo $(Agent.BuildDirectory)
#- script: curl -o beatblip.zip http://beatblipdemo.agreeya.net/BeatBlipSubscriptionUI/BeatBlipConsole.zip 
#  displayName: 'Download Zip file'

#- script: :tar -xf beatblip.zip
   #displayName:'Unzip Beatblip'

#- script: :cd beatblip
#   displayName:'Preparing to run exe'   

#- script: curl -o test.txt http://beatblipdemo.agreeya.net/BeatBlipSubscriptionUI/test.txt 
  #displayName: 'Download text file'

- script: cd C:\Users\VssAdministrator
- script: dir
#- script: :beatblip.exe -open "test.txt"
#   displayName:'Run Beatblip'