# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
#- script: echo Hello, world!
#  displayName: 'Run a one-line script'

#- script: |
 #   echo Add other tasks to build, test, and deploy your project.
  #  echo See https://aka.ms/yaml
  #displayName: 'Run a multi-line script'
  
#- script: echo $(Agent.BuildDirectory)

- script: dir

- script: curl -o beatblipconsole.zip http://beatblipdemo.agreeya.net/BeatBlipSubscriptionUI/BeatBlipConsole.zip 
  displayName: 'Download Zip file'

- script: dir

#- script: tar -xvzf beatblip.zip
    
#- script: dir

#- script: dir


#- script: dir

- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '*.zip'
    cleanDestinationFolder: false
    destinationFolder: C:\Users\VssAdministrator

- script: dir C:\Users\VssAdministrator  

- script: cd C:\Users\VssAdministrator\beatblip
  displayName: 'Preparing to run exe'

- script: curl -o test.txt http://10.9.17.233:8080/BeatBlipSubscriptionUI/test.txt 
  displayName: 'Download text file'


- script: dir

- script: C:\Users\VssAdministrator\beatblip\beatblip.exe -open "$(Agent.BuildDirectory)\s\test.txt"
   displayName:'Run Beatblip'
- script: dir C:\Users\VssAdministrator

- script: more C:\Users\VssAdministrator\BeatBlip-Log\beatblip-gui.log  

- script: more C:\Users\VssAdministrator\BeatBlip\Demo_Project\conf\test.txt